In [99]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np

#sklearn
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

Reading our data

In [100]:
df = pd.read_csv("Score.csv")
df

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit_Mix,...,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,3.0,7.0,4.0,26.822620,265.0,No,80.415295,312.494089,Good,Good,...,23.0,19114.12,3.0,4.0,3.0,4.0,1824.843333,11.27,809.98,49.574949
1,3.0,7.0,4.0,31.944960,265.0,No,118.280222,284.629162,Good,Good,...,23.0,19114.12,3.0,4.0,3.0,4.0,1824.843333,11.27,809.98,49.574949
2,3.0,7.0,4.0,28.609352,267.0,No,81.699521,331.209863,Good,Good,...,23.0,19114.12,3.0,4.0,3.0,4.0,1824.843333,11.27,809.98,49.574949
3,5.0,4.0,4.0,31.377862,268.0,No,199.458074,223.451310,Good,Good,...,23.0,19114.12,3.0,4.0,3.0,4.0,1824.843333,11.27,809.98,49.574949
4,6.0,4.0,4.0,24.797347,269.0,No,41.420153,341.489231,Good,Good,...,23.0,19114.12,3.0,4.0,3.0,4.0,1824.843333,11.27,809.98,49.574949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99955,23.0,7.0,3.0,34.663572,378.0,No,60.971333,479.866228,Poor,Good,...,25.0,39628.99,4.0,6.0,7.0,2.0,3359.415833,11.50,502.38,35.104023
99956,18.0,7.0,3.0,40.565631,379.0,No,54.185950,496.651610,Poor,Good,...,25.0,39628.99,4.0,6.0,7.0,2.0,3359.415833,11.50,502.38,35.104023
99957,27.0,6.0,3.0,41.255522,380.0,No,24.028477,516.809083,Poor,Good,...,25.0,39628.99,4.0,6.0,7.0,2.0,3359.415833,11.50,502.38,35.104023
99958,20.0,6.0,3.0,33.638208,381.0,No,251.672582,319.164979,Standard,Good,...,25.0,39628.99,4.0,6.0,7.0,2.0,3359.415833,11.50,502.38,35.104023
99959,18.0,6.0,3.0,34.192463,382.0,No,167.163865,393.673696,Poor,Good,...,25.0,39628.99,4.0,6.0,7.0,2.0,3359.415833,11.50,502.38,35.104023

In [101]:
#Checking whether there is any Null value in the Dataset
df.isna().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Score                0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

In [102]:
#Defining into numeric_cols and categorical_cols inorder to fill the numeric value
numeric_cols = df.select_dtypes(include = np.number).columns.tolist()
categorical_cols = df.select_dtypes(include = "object").columns.tolist()

In [103]:
numeric_cols

['Delay_from_due_date',
 'Num_of_Delayed_Payment',
 'Num_Credit_Inquiries',
 'Credit_Utilization_Ratio',
 'Credit_History_Age',
 'Amount_invested_monthly',
 'Monthly_Balance',
 'Age',
 'Annual_Income',
 'Num_Bank_Accounts',
 'Num_Credit_Card',
 'Interest_Rate',
 'Num_of_Loan',
 'Monthly_Inhand_Salary',
 'Changed_Credit_Limit',
 'Outstanding_Debt',
 'Total_EMI_per_month']

In [104]:
categorical_cols

['Payment_of_Min_Amount', 'Credit_Score', 'Credit_Mix', 'Payment_Behaviour']

In [105]:
df[numeric_cols].isna().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Amount_invested_monthly     0
Monthly_Balance             0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

#Filling our Null Numeric Value

In [106]:
imputer = SimpleImputer(strategy="mean")
imputer.fit(df[numeric_cols])

SimpleImputer()

In [107]:
df[numeric_cols] = imputer.transform(df[numeric_cols])

In [108]:
df[numeric_cols].isna().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Amount_invested_monthly     0
Monthly_Balance             0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

Our numeric valued dataset is successfully cleaned and there is no null value in it

#Fill the null Categorical value

In [109]:
imputer = SimpleImputer(strategy="most_frequent")
imputer.fit(df[categorical_cols])
df[categorical_cols] = imputer.transform(df[categorical_cols])

In [110]:
df[categorical_cols].isna().sum()

Payment_of_Min_Amount    0
Credit_Score             0
Credit_Mix               0
Payment_Behaviour        0
dtype: int64

categorical null value has been cleaned

In [111]:
#Checking overall Dataset whether it is fully cleaned or not
df.isna().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Score                0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

#Converting the categorical value into numeric value

In [112]:
df[categorical_cols].describe()

,Payment_of_Min_Amount,Credit_Score,Credit_Mix,Payment_Behaviour
count,99960,99960,99960,99960
unique,3,3,3,6
top,Yes,Standard,Standard,Low_spent_Small_value_payments
freq,52326,53149,45832,33912

In [113]:
df["Payment_of_Min_Amount"].unique()

array(['No', 'NM', 'Yes'], dtype=object)

In [114]:
df[categorical_cols]

,Payment_of_Min_Amount,Credit_Score,Credit_Mix,Payment_Behaviour
0,No,Good,Good,High_spent_Medium_value_payments
1,No,Good,Good,High_spent_Medium_value_payments
2,No,Good,Good,High_spent_Medium_value_payments
3,No,Good,Good,High_spent_Medium_value_payments
4,No,Good,Good,High_spent_Medium_value_payments
...,...,...,...,...
99955,No,Poor,Good,High_spent_Medium_value_payments
99956,No,Poor,Good,High_spent_Medium_value_payments
99957,No,Poor,Good,High_spent_Medium_value_payments
99958,No,Standard,Good,High_spent_Medium_value_payments
99959,No,Poor,Good,High_spent_Medium_value_payments

In [115]:
df["Payment_of_Min_Amount"].value_counts()
#Here NM is not well defined in the dataset so we will remove the value containing NM
df = df[df["Payment_of_Min_Amount"]!="NM"]

In [116]:
df["Payment_of_Min_Amount"].value_counts()

Yes    52326
No     35628
Name: Payment_of_Min_Amount, dtype: int64

In [117]:
df["Credit_Score"].value_counts()

Standard    46906
Poor        25470
Good        15578
Name: Credit_Score, dtype: int64

In [118]:
df["Credit_Mix"].value_counts()

Standard    40339
Good        26697
Bad         20918
Name: Credit_Mix, dtype: int64

In [119]:
df["Payment_Behaviour"].value_counts()

Low_spent_Small_value_payments      29897
High_spent_Medium_value_payments    23466
High_spent_Large_value_payments     14740
Low_spent_Medium_value_payments      9033
High_spent_Small_value_payments      5752
Low_spent_Large_value_payments       5066
Name: Payment_Behaviour, dtype: int64

We can map the value for the column Credit_Score , Credit_Mix , Payment_of_Min_Amount as it contains less values

In [120]:
payment_of_min_amount_values = {"Yes" : 1 , "No" : 0}
df["Payment_of_Min_Amount"] = df["Payment_of_Min_Amount"].replace(payment_of_min_amount_values)

<ipython-input-120-0356f9d45abb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_of_Min_Amount"] = df["Payment_of_Min_Amount"].replace(payment_of_min_amount_values)

In [121]:
credit_score_values = {"Poor" : 0 , "Standard" : 1 , "Good" : 2}
df["Credit_Score"] = df["Credit_Score"].replace(credit_score_values)

<ipython-input-121-7e0a5406b01b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Credit_Score"] = df["Credit_Score"].replace(credit_score_values)

In [122]:
credit_mix_values = {"Bad" : 0 , "Standard" : 1 , "Good" : 2}
df["Credit_Mix"] = df["Credit_Mix"].replace(credit_mix_values)

<ipython-input-122-3a423ea36fd8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Credit_Mix"] = df["Credit_Mix"].replace(credit_mix_values)

In [123]:
categorical_cols = df.select_dtypes("object").columns.tolist()

Encoding categorical value to Numeric value for the column Payment Behaviour

In [124]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse = False , handle_unknown = "ignore").fit(df[categorical_cols])
encoded_cols = list(enc.get_feature_names_out(categorical_cols))
df[encoded_cols] = enc.transform(df[categorical_cols])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
<ipython-input-124-f6af3a8bd06d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[encoded_cols] = enc.transform(df[categorical_cols])
<ipython-input-124-f6af3a8bd06d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[encoded_cols] = enc.transform(df[categorical_cols])
<ipython-input-124-f6af3a8bd06d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[encoded_cols] = enc.transform(df[categorical_cols])
<ipython-input-124-f6af3a8bd06d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[encoded_cols] = enc.transform(df[categorical_cols])
<ipython-input-124-f6af3a8bd06d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[encoded_cols] = enc.transform(df[categorical_cols])
<ipython-input-124-f6af3a8bd06d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[encoded_cols] = enc.transform(df[categorical_cols])

In [125]:
df

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit_Mix,...,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month,Payment_Behaviour_High_spent_Large_value_payments,Payment_Behaviour_High_spent_Medium_value_payments,Payment_Behaviour_High_spent_Small_value_payments,Payment_Behaviour_Low_spent_Large_value_payments,Payment_Behaviour_Low_spent_Medium_value_payments,Payment_Behaviour_Low_spent_Small_value_payments
0,3.0,7.0,4.0,26.822620,265.0,0,80.415295,312.494089,2,2,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
1,3.0,7.0,4.0,31.944960,265.0,0,118.280222,284.629162,2,2,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
2,3.0,7.0,4.0,28.609352,267.0,0,81.699521,331.209863,2,2,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
3,5.0,4.0,4.0,31.377862,268.0,0,199.458074,223.451310,2,2,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
4,6.0,4.0,4.0,24.797347,269.0,0,41.420153,341.489231,2,2,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99955,23.0,7.0,3.0,34.663572,378.0,0,60.971333,479.866228,0,2,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99956,18.0,7.0,3.0,40.565631,379.0,0,54.185950,496.651610,0,2,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99957,27.0,6.0,3.0,41.255522,380.0,0,24.028477,516.809083,0,2,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99958,20.0,6.0,3.0,33.638208,381.0,0,251.672582,319.164979,1,2,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99959,18.0,6.0,3.0,34.192463,382.0,0,167.163865,393.673696,0,2,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0

In [126]:
#Moving the Target col to last
df["Credit_Score"] = df.pop("Credit_Score")

<ipython-input-126-9bf741b80e7f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Credit_Score"] = df.pop("Credit_Score")

In [127]:
df

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Payment_Behaviour,...,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month,Payment_Behaviour_High_spent_Large_value_payments,Payment_Behaviour_High_spent_Medium_value_payments,Payment_Behaviour_High_spent_Small_value_payments,Payment_Behaviour_Low_spent_Large_value_payments,Payment_Behaviour_Low_spent_Medium_value_payments,Payment_Behaviour_Low_spent_Small_value_payments,Credit_Score
0,3.0,7.0,4.0,26.822620,265.0,0,80.415295,312.494089,2,High_spent_Medium_value_payments,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
1,3.0,7.0,4.0,31.944960,265.0,0,118.280222,284.629162,2,High_spent_Medium_value_payments,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
2,3.0,7.0,4.0,28.609352,267.0,0,81.699521,331.209863,2,High_spent_Medium_value_payments,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
3,5.0,4.0,4.0,31.377862,268.0,0,199.458074,223.451310,2,High_spent_Medium_value_payments,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
4,6.0,4.0,4.0,24.797347,269.0,0,41.420153,341.489231,2,High_spent_Medium_value_payments,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99955,23.0,7.0,3.0,34.663572,378.0,0,60.971333,479.866228,2,High_spent_Medium_value_payments,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0
99956,18.0,7.0,3.0,40.565631,379.0,0,54.185950,496.651610,2,High_spent_Medium_value_payments,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0
99957,27.0,6.0,3.0,41.255522,380.0,0,24.028477,516.809083,2,High_spent_Medium_value_payments,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0
99958,20.0,6.0,3.0,33.638208,381.0,0,251.672582,319.164979,2,High_spent_Medium_value_payments,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,1
99959,18.0,6.0,3.0,34.192463,382.0,0,167.163865,393.673696,2,High_spent_Medium_value_payments,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0

In [128]:
df.pop("Payment_Behaviour")

0        High_spent_Medium_value_payments
1        High_spent_Medium_value_payments
2        High_spent_Medium_value_payments
3        High_spent_Medium_value_payments
4        High_spent_Medium_value_payments
                       ...
99955    High_spent_Medium_value_payments
99956    High_spent_Medium_value_payments
99957    High_spent_Medium_value_payments
99958    High_spent_Medium_value_payments
99959    High_spent_Medium_value_payments
Name: Payment_Behaviour, Length: 87954, dtype: object

In [129]:
df.select_dtypes("object").columns.tolist()

[]

In [130]:
df

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Age,...,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month,Payment_Behaviour_High_spent_Large_value_payments,Payment_Behaviour_High_spent_Medium_value_payments,Payment_Behaviour_High_spent_Small_value_payments,Payment_Behaviour_Low_spent_Large_value_payments,Payment_Behaviour_Low_spent_Medium_value_payments,Payment_Behaviour_Low_spent_Small_value_payments,Credit_Score
0,3.0,7.0,4.0,26.822620,265.0,0,80.415295,312.494089,2,23.0,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
1,3.0,7.0,4.0,31.944960,265.0,0,118.280222,284.629162,2,23.0,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
2,3.0,7.0,4.0,28.609352,267.0,0,81.699521,331.209863,2,23.0,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
3,5.0,4.0,4.0,31.377862,268.0,0,199.458074,223.451310,2,23.0,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
4,6.0,4.0,4.0,24.797347,269.0,0,41.420153,341.489231,2,23.0,...,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99955,23.0,7.0,3.0,34.663572,378.0,0,60.971333,479.866228,2,25.0,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0
99956,18.0,7.0,3.0,40.565631,379.0,0,54.185950,496.651610,2,25.0,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0
99957,27.0,6.0,3.0,41.255522,380.0,0,24.028477,516.809083,2,25.0,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0
99958,20.0,6.0,3.0,33.638208,381.0,0,251.672582,319.164979,2,25.0,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,1
99959,18.0,6.0,3.0,34.192463,382.0,0,167.163865,393.673696,2,25.0,...,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0,0

Splitting the data to input and output

In [131]:
y = df["Credit_Score"]
x = df.iloc[:,:-1]

In [132]:
x

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Age,...,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month,Payment_Behaviour_High_spent_Large_value_payments,Payment_Behaviour_High_spent_Medium_value_payments,Payment_Behaviour_High_spent_Small_value_payments,Payment_Behaviour_Low_spent_Large_value_payments,Payment_Behaviour_Low_spent_Medium_value_payments,Payment_Behaviour_Low_spent_Small_value_payments
0,3.0,7.0,4.0,26.822620,265.0,0,80.415295,312.494089,2,23.0,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
1,3.0,7.0,4.0,31.944960,265.0,0,118.280222,284.629162,2,23.0,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
2,3.0,7.0,4.0,28.609352,267.0,0,81.699521,331.209863,2,23.0,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
3,5.0,4.0,4.0,31.377862,268.0,0,199.458074,223.451310,2,23.0,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
4,6.0,4.0,4.0,24.797347,269.0,0,41.420153,341.489231,2,23.0,...,1824.843333,11.27,809.98,49.574949,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99955,23.0,7.0,3.0,34.663572,378.0,0,60.971333,479.866228,2,25.0,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99956,18.0,7.0,3.0,40.565631,379.0,0,54.185950,496.651610,2,25.0,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99957,27.0,6.0,3.0,41.255522,380.0,0,24.028477,516.809083,2,25.0,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99958,20.0,6.0,3.0,33.638208,381.0,0,251.672582,319.164979,2,25.0,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0
99959,18.0,6.0,3.0,34.192463,382.0,0,167.163865,393.673696,2,25.0,...,3359.415833,11.50,502.38,35.104023,0.0,1.0,0.0,0.0,0.0,0.0

In [133]:
y = pd.DataFrame(y)
y.value_counts()

Credit_Score
1               46906
0               25470
2               15578
dtype: int64

#Splitting our data into Train , Test

In [134]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

In [135]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((70363, 25), (17591, 25), (70363, 1), (17591, 1))

There is no Categorical columns in our dataset as we converted all of them to numeric

#Load the DataSet :

In [136]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader

In [137]:
class CustomDataset(Dataset):
  def __init__(self,data,label):
    self.data = torch.tensor(data.values).type(torch.float32)
    self.label = torch.tensor(label.values)

  def __len__(self):
    return len(self.data)

  def __getitem__(self,index):
    return self.data[index] , self.label[index]

In [138]:
dataset = CustomDataset(x_train , y_train)

In [139]:
batch_size = 2
train_loader = DataLoader(dataset , batch_size = batch_size , shuffle = True)

In [140]:
class NeuralNetworks(nn.Module):
  def __init__(self,in_features,out_features,hidden_units):
    super().__init__()

    self.layer = nn.Sequential(
    nn.Linear(in_features = in_features , out_features = hidden_units),
    nn.ReLU(),
    nn.Linear(in_features = hidden_units , out_features = hidden_units),
    nn.ReLU(),
    nn.Linear(in_features = hidden_units , out_features = out_features)
    )

  def forward(self,x):
    return self.layer(x)

In [141]:
model = NeuralNetworks(in_features = 25 , out_features = 3 , hidden_units = 100)

Loss func , Optimizer func , Accuracy func

In [142]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params = model.parameters() , lr = 0.01)

In [143]:
def accuracy(train_preds , y_train):
  acc = torch.eq(train_preds , y_train).sum().item()
  return acc/len(train_preds)

In [144]:
#Random Seed
torch.manual_seed(42)

epochs = 10

for epoch in range(epochs):

  for input , target in train_loader:

    model.train()

    #Forward method
    train_logits = model(input)
    train_preds = torch.softmax(train_logits,1).argmax(dim = 1)
    target = target.view(-1)
    #target = target.type(torch.LongTensor)

    #Calculate the loss
    train_loss = loss_fn(train_logits,target)
    train_accuracy = accuracy(train_preds,target)*100

    #Optimizer
    optimizer.zero_grad

    #LossBackward
    train_loss.backward()

    #Optimizer.step
    optimizer.step()

print(f'epoch : {epoch}\ntrain_loss = {train_loss.item()} , train_accuracy : {train_accuracy}')

epoch : 9
train_loss = 0.09160928428173065 , train_accuracy : 100.0

The accuracy is 100% in Neural Networks !!!!!!!!!!!!!!!!!!!!

In [150]:
test_dataset = CustomDataset(x_train,y_train)
train_loader = DataLoader(test_dataset ,batch_size = 2 , shuffle = True)

In [155]:
epochs = 11
model.eval()
with torch.inference_mode():
  for epoch in range(epochs) :
    for inputs,target in train_loader:
      test_logits = model(inputs)
      test_preds = torch.softmax(test_logits,1).argmax(dim=1)
      target = target.view(-1)

      #Loss and accuracy
      test_loss = loss_fn(test_logits,target)
      test_accuracy = accuracy(test_preds , target)*100

print(f'epoch : {epoch}\ntest_loss = {test_loss.item()} , test_accuracy : {test_accuracy}')

epoch : 10
test_loss = 0.09340950101613998 , test_accuracy : 100.0